/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://77s7xtgb5rgyfgcgji3pomjcwi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kz4hnf43hbbtrdnni3kgiesdgq",
    "aws_cognito_identity_pool_id": "ap-south-1:c1e49642-4ab0-4bfe-8ed2-c69e43c74f70",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_PII58O0nC",
    "aws_user_pools_web_client_id": "5spsb7eltfdkub97r7j4svm5f5",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
